apiVersion: v1
kind: Service
metadata:
  name: pdf-sign-packing
  namespace: blpid-pdfsignpacking-dev
  labels:
    app: pdf-sign-packing
spec:
  selector:
    app: pdf-sign-packing
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP